package com.example.beproducktive.ui.projects

import android.view.LayoutInflater
import android.view.ViewGroup
import androidx.recyclerview.widget.RecyclerView
import com.example.beproducktive.R
import com.example.beproducktive.data.projects.Project
import com.example.beproducktive.databinding.ItemProjectBinding

class ProjectsViewHolder (
    private val binding: ItemProjectBinding // autogenerated
) : RecyclerView.ViewHolder(binding.root)
{
    fun bind(project: Project){
        binding.apply {
            textviewProjectName.text = "Project: ${project.projectName}".uppercase()
        }
    }

    companion object {
        fun create(parent: ViewGroup) : ProjectsViewHolder {
            val view = LayoutInflater.from(parent.context)
                .inflate(R.layout.item_project, parent, false)
            val binding = ItemProjectBinding.bind(view)
            return ProjectsViewHolder(binding)
        }
    }
}